FROM --platform=linux/amd64 node:20-bookworm

# Install extra system packages
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      curl gnupg xz-utils xvfb zypper binutils libasound2 \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /project

RUN npm --silent install --global --depth 0 pnpm