version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/app-builder-lib"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/builder-util"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/builder-util-runtime"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/dmg-builder"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/electron-builder"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/electron-builder-squirrel-windows"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/electron-forge-maker-appimage"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/electron-forge-maker-nsis"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/electron-forge-maker-nsis-web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/electron-forge-maker-snap"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/electron-publish"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/electron-updater"
    schedule:
      interval: "weekly"



