critical:
  - '(critical|urgent)'
appimage:
  - appimage
appx:
  - appx
bug:
  - ' bug '
docker:
  - docker
electron-updater:
  - updater
linux:
  - linux
  - ubuntu
  - fedora
mac:
  - mac
  - macos
windows:
  - windows
msi:
  - msi
nsis:
  - nsis
readme:
  - '(docs|readme)'
snap:
  - '(snap|snaps|snapcraft)'
flatpak:
  - '(flat|flatpak|flatpack)'
squirrel.windows:
  - squirrel
electron-publish:
  - publish
