app-builder-lib:
  - changed-files:
    - any-glob-to-any-file:
      - packages/app-builder-lib/**/*
builder-util:
  - changed-files:
    - any-glob-to-any-file:
      - packages/builder-util/**/*
      - packages/builder-util-runtime/**/*
dmg-builder:
  - changed-files:
    - any-glob-to-any-file:
      - packages/dmg-builder/**/*
mac:
  - changed-files:
    - any-glob-to-any-file:
      - packages/dmg-builder/**/*
      - '**/mac*.ts'
linux:
  - changed-files:
    - any-glob-to-any-file:
      - '**/linux*.ts'
windows:
  - changed-files:
    - any-glob-to-any-file:
      - '**/win*.ts'
squirrel.windows:
  - changed-files:
    - any-glob-to-any-file:
      - packages/electron-builder-squirrel-windows/**/*
appimage:
  - changed-files:
    - any-glob-to-any-file:
      - packages/electron-forge-maker-appimage/**/*
nsis:
  - changed-files:
    - any-glob-to-any-file:
      - packages/app-builder-lib/src/targets/nsis/*
      - packages/electron-forge-maker-nsis/**/*
      - packages/electron-forge-maker-nsis-web/**/*
snap:
  - changed-files:
    - any-glob-to-any-file:
      - packages/electron-forge-maker-snap/**/*
electron-publish:
  - changed-files:
    - any-glob-to-any-file:
      - packages/electron-publish/**/*
electron-updater:
  - changed-files:
    - any-glob-to-any-file:
      - packages/electron-updater/**/*
