  app-builder-lib:
  - changed-files:
    - any-glob-to-any-file:
      - packages/app-builder-lib/**/*
  builder-util:
  - changed-files:
    - any-glob-to-any-file:
      - packages/builder-util/**/*
  builder-util-runtime:
  - changed-files:
    - any-glob-to-any-file:
      - packages/builder-util-runtime/**/*
  dmg-builder:
  - changed-files:
    - any-glob-to-any-file:
      - packages/dmg-builder/**/*
  electron-builder:
  - changed-files:
    - any-glob-to-any-file:
      - packages/electron-builder/**/*
  electron-builder-squirrel-windows:
  - changed-files:
    - any-glob-to-any-file:
      - packages/electron-builder-squirrel-windows/**/*
  electron-publish:
  - changed-files:
    - any-glob-to-any-file:
      - packages/electron-publish/**/*
  electron-updater:
  - changed-files:
    - any-glob-to-any-file:
      - packages/electron-updater/**/*