packages:
  - "packages/**"
  - "test"

# 10080 minutes = 7 days
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "tar"
  - "@electron/rebuild"
  # Renovate security update: minimatch@10.2.3
  - minimatch@10.2.3
