packages:
  - "packages/**"
  - "test"

allowBuilds:
  '@parcel/watcher': false
  electron: false
  electron-winstaller: true
  esbuild: false

# 10080 minutes = 7 days
minimumReleaseAge: 10080
patchedDependencies:
  '@changesets/cli@2.29.7': patches/@changesets__cli@2.29.7.patch
  '@changesets/assemble-release-plan@6.0.9': patches/@changesets__assemble-release-plan@6.0.9.patch
overrides:
  flatted: '>=3.4.2'
  handlebars: '>=4.7.9'
packageImportMethod: copy
