import * as fs from "fs"
import * as path from "path"
import type { ToolsetConfig } from "app-builder-lib/internal"
import { buildDescribeCall, cleanAndEnsureDir, GENERATED_TESTS_DIR, getPlatformSuffix, namedFn, resolveImportPath, TEST_SRC_DIR } from "./generate-toolset-tests-shared"
import type { SuiteConfig } from "./generate-toolset-tests-shared"
import { WINE_VERSIONS } from "./generate-toolset-versions"
import type * as _WineToolsetSuite from "../../src/mac/wineToolsetSuite"

const SUITES: SuiteConfig[] = [
  {
    name: "wineToolset",
    registerFn: namedFn("registerWineToolsetTests" satisfies keyof typeof _WineToolsetSuite),
    importPath: "mac/wineToolsetSuite",
    // ifNotWindows: wine runs on macOS and Linux; the suite itself also uses describe.ifNotWindows.
    // Suffix "__" (no platform marker) means discovered everywhere; Windows skips via the inner guard.
    describeConfig: { name: "wine", chain: ["ifNotWindows"] },
  },
]

function renderFile(suite: SuiteConfig, version: ToolsetConfig["wine"]): string {
  const fnName = suite.registerFn.name
  const toolsetsArg = JSON.stringify({ wine: version })
  const describeCall = buildDescribeCall(suite.describeConfig.chain)
  const optionsPart = suite.describeOptions ? `, ${JSON.stringify(suite.describeOptions)}` : ""

  const body = `${describeCall}("${suite.describeConfig.name}"${optionsPart}, () => {
  ${fnName}(${toolsetsArg})
})`

  const generatedDir = path.resolve(GENERATED_TESTS_DIR, suite.name)
  const importPath = resolveImportPath(generatedDir, TEST_SRC_DIR, suite.importPath)
  return `// @generated — do not edit. Regenerated by generate-toolset-tests-mac.ts on each test run.
import { ${fnName} } from "${importPath}"

${body}
`
}

export const MAC_SUITE_METADATA = SUITES.map(s => ({ name: s.name, chain: s.describeConfig.chain }))

export function generateMacToolsetTests(): void {
  for (const suite of SUITES) {
    const generatedDir = path.resolve(GENERATED_TESTS_DIR, suite.name)
    cleanAndEnsureDir(generatedDir)
    const platformSuffix = getPlatformSuffix(suite.describeConfig.chain)
    for (const version of WINE_VERSIONS) {
      const filename = `${suite.name}__wine-${version}${platformSuffix}Test.ts`
      fs.writeFileSync(path.join(generatedDir, filename), renderFile(suite, version), "utf8")
    }
  }
}
