BrandingText "${PRODUCT_NAME} ${VERSION}"
ShowInstDetails nevershow
ShowUninstDetails nevershow
FileBufSize 64
Name "${PRODUCT_NAME}"
Unicode true

!define MULTIUSER_INSTALLMODE_DEFAULT_REGISTRY_VALUENAME "UninstallString"
!define MULTIUSER_INSTALLMODE_INSTDIR_REGISTRY_VALUENAME "InstallLocation"

!define MULTIUSER_INSTALLMODE_INSTDIR "${APP_GUID}"
!define MULTIUSER_INSTALLMODE_INSTALL_REGISTRY_KEY "${APP_GUID}"
!define MULTIUSER_INSTALLMODE_UNINSTALL_REGISTRY_KEY "${APP_GUID}"

!define APP_EXECUTABLE_FILENAME "${PRODUCT_NAME}.exe"
!define UNINSTALL_FILENAME "Uninstall ${PRODUCT_NAME}.exe"