name: 'Setup Tests'
description: 'Set up pnpm, node w/ pnpm cache, install and audit deps, compile, and restore electron cache'
inputs:
  cache-key:
    description: 'The key to the electron cache'
    required: true
  cache-path:
    description: 'The path to the electron cache'
    required: true
  version:
    description: 'The pnpm version to use'
    required: false
    default: 8.6.5

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # tag=v2.2.4
      with:
        version: ${{ inputs.version }}

    - name: Setup node
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Compile
      run: pnpm compile
      shell: bash
    
    - name: Cache Electron
      uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0 # v3
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}

## Usage
# - name: Setup Tests
#   uses: ./.github/actions/pretest
#   with:
#     cache-path: ~/Library/Caches/electron
#     cache-key: v-17.0.0-macos-electron
