name: 'Setup Tests'
description: 'Set up pnpm, node w/ pnpm cache, install deps, compile, and restore electron cache'
inputs:
  cache-key:
    description: 'The key to the electron cache'
    required: true
  cache-path:
    description: 'The path to the electron cache'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Enable Corepack for pnpm
      run: |
        corepack enable
        corepack prepare pnpm@10.18.0 --activate
      shell: bash

    - name: Setup python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'

    - name: Setup node
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: '22'
        cache: 'pnpm'

    - name: Install bun globally
      run: |
        npm install -g bun@1.3.2
      shell: bash

    - name: Update npm to mirror pr-release workflow environment
      run: npm install -g npm@11.6.2
      shell: bash

    - name: Verify updated npm version
      run: npm -v
      shell: bash

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Compile
      run: pnpm compile
      shell: bash

    - name: Cache Electron
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}

## Usage
# - name: Setup Tests
#   uses: ./.github/actions/pretest
#   with:
#     cache-path: ~/Library/Caches/electron
#     cache-key: v-35.7.5-macos-electron
