name: 'Setup Tests'
description: 'Set up pnpm, node w/ pnpm cache, install and audit deps, compile, and restore electron cache'
inputs:
  cache-key:
    description: 'The key to the electron cache'
    required: true
  cache-path:
    description: 'The path to the electron cache'
    required: true
  version:
    description: 'The pnpm version to use'
    required: false
    default: 7.1.6

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: ${{ inputs.version }}

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Compile
      run: pnpm compile
      shell: bash
    
    - name: Cache Electron
      uses: actions/cache@v2
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}

## Usage
# - name: Setup Tests
#   uses: ./.github/actions/pretest
#   with:
#     cache-path: ~/Library/Caches/electron
#     cache-key: v-11.0.0-macos-electron