name: 'pnpm installation'
description: 'Install and audit dependencies via pnpm'
inputs:
  version: # id of input
    description: 'The pnpm version to use'
    required: false
    default: 7.1.6

runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'pnpm'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.version }}

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

## Usage
# - name: install and audit
#   uses: ./.github/actions/pnpm
#   with:
#     version: ${{ env.PNPM_VERSION }}