name: 'pnpm installation'
description: 'Install and audit dependencies via pnpm'
inputs:
  version: # id of input
    description: 'The pnpm version to use'
    required: false
    default: 8.6.10

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # tag=v2.2.4
      with:
        version: ${{ inputs.version }}

    - name: Setup node
      uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

## Usage
# - name: install and audit
#   uses: ./.github/actions/pnpm
#   with:
#     version: ${{ env.PNPM_VERSION }}
