name: 'pnpm installation'
description: 'Install and audit dependencies via pnpm'
inputs:
  version: # id of input
    description: 'The pnpm version to use'
    required: false
    default: 8.6.10

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
      with:
        version: ${{ inputs.version }}

    - name: Setup node
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

## Usage
# - name: install and audit
#   uses: ./.github/actions/pnpm
#   with:
#     version: ${{ env.PNPM_VERSION }}
