import pathSorter from "path-sort"

//noinspection SpellCheckingInspection
export const expectedLinuxContents = ["/",
  "/opt/",
  "/usr/",
  "/opt/TestApp/",
  "/opt/TestApp/blink_image_resources_200_percent.pak",
  "/opt/TestApp/content_resources_200_percent.pak",
  "/opt/TestApp/content_shell.pak",
  "/opt/TestApp/icudtl.dat",
  "/opt/TestApp/libffmpeg.so",
  "/opt/TestApp/libnode.so",
  "/opt/TestApp/LICENSE.electron.txt",
  "/opt/TestApp/LICENSES.chromium.html",
  "/opt/TestApp/natives_blob.bin",
  "/opt/TestApp/snapshot_blob.bin",
  "/opt/TestApp/testapp",
  "/opt/TestApp/ui_resources_200_percent.pak",
  "/opt/TestApp/views_resources_200_percent.pak",
  "/usr/share/",
  "/opt/TestApp/resources/",
  "/opt/TestApp/resources/app.asar",
  "/opt/TestApp/resources/electron.asar",
  "/usr/share/applications/",
  "/usr/share/applications/TestApp.desktop",
  "/usr/share/doc/",
  "/usr/share/icons/",
  "/usr/share/doc/testapp/",
  "/usr/share/doc/testapp/changelog.gz",
  "/usr/share/icons/hicolor/",
  "/usr/share/icons/hicolor/128x128/",
  "/usr/share/icons/hicolor/16x16/",
  "/usr/share/icons/hicolor/24x24/",
  "/usr/share/icons/hicolor/256x256/",
  "/usr/share/icons/hicolor/32x32/",
  "/usr/share/icons/hicolor/48x48/",
  "/usr/share/icons/hicolor/512x512/",
  "/usr/share/icons/hicolor/64x64/",
  "/usr/share/icons/hicolor/96x96/",
  "/usr/share/icons/hicolor/128x128/apps/",
  "/usr/share/icons/hicolor/128x128/apps/TestApp.png",
  "/usr/share/icons/hicolor/16x16/apps/",
  "/usr/share/icons/hicolor/16x16/apps/TestApp.png",
  "/usr/share/icons/hicolor/24x24/apps/",
  "/usr/share/icons/hicolor/24x24/apps/TestApp.png",
  "/usr/share/icons/hicolor/256x256/apps/",
  "/usr/share/icons/hicolor/256x256/apps/TestApp.png",
  "/usr/share/icons/hicolor/32x32/apps/",
  "/usr/share/icons/hicolor/32x32/apps/TestApp.png",
  "/usr/share/icons/hicolor/48x48/apps/",
  "/usr/share/icons/hicolor/48x48/apps/TestApp.png",
  "/usr/share/icons/hicolor/512x512/apps/",
  "/usr/share/icons/hicolor/512x512/apps/TestApp.png",
  "/usr/share/icons/hicolor/64x64/apps/",
  "/usr/share/icons/hicolor/64x64/apps/TestApp.png",
  "/usr/share/icons/hicolor/96x96/apps/",
  "/usr/share/icons/hicolor/96x96/apps/TestApp.png"]

//noinspection SpellCheckingInspection
export const expectedWinContents = [
  "lib/net45/blink_image_resources_200_percent.pak",
  "lib/net45/content_resources_200_percent.pak",
  "lib/net45/content_shell.pak",
  "lib/net45/d3dcompiler_47.dll",
  "lib/net45/ffmpeg.dll",
  "lib/net45/icudtl.dat",
  "lib/net45/libEGL.dll",
  "lib/net45/libGLESv2.dll",
  "lib/net45/LICENSE.electron.txt",
  "lib/net45/LICENSES.chromium.html",
  "lib/net45/natives_blob.bin",
  "lib/net45/node.dll",
  "lib/net45/snapshot_blob.bin",
  "lib/net45/TestApp.exe",
  "lib/net45/ui_resources_200_percent.pak",
  "lib/net45/Update.exe",
  "lib/net45/views_resources_200_percent.pak",
  "lib/net45/xinput1_3.dll",
  "lib/net45/locales/en-US.pak",
  "lib/net45/resources/app.asar",
  "lib/net45/resources/electron.asar",
  "TestApp.nuspec",
  "[Content_Types].xml",
  "_rels/.rels"
]

export const nsisPerMachineInstall = pathSorter([
  "Program Files/TestApp",
  "Program Files/TestApp/1.1.0",
  "Program Files/TestApp/1.1.0/blink_image_resources_200_percent.pak",
  "Program Files/TestApp/1.1.0/content_resources_200_percent.pak",
  "Program Files/TestApp/1.1.0/content_shell.pak",
  "Program Files/TestApp/1.1.0/d3dcompiler_47.dll",
  "Program Files/TestApp/1.1.0/ffmpeg.dll",
  "Program Files/TestApp/1.1.0/icudtl.dat",
  "Program Files/TestApp/1.1.0/libEGL.dll",
  "Program Files/TestApp/1.1.0/libGLESv2.dll",
  "Program Files/TestApp/1.1.0/LICENSE.electron.txt",
  "Program Files/TestApp/1.1.0/LICENSES.chromium.html",
  "Program Files/TestApp/1.1.0/locales",
  "Program Files/TestApp/1.1.0/natives_blob.bin",
  "Program Files/TestApp/1.1.0/node.dll",
  "Program Files/TestApp/1.1.0/resources",
  "Program Files/TestApp/1.1.0/snapshot_blob.bin",
  "Program Files/TestApp/1.1.0/TestApp.exe",
  "Program Files/TestApp/1.1.0/ui_resources_200_percent.pak",
  "Program Files/TestApp/1.1.0/Uninstall TestApp.exe",
  "Program Files/TestApp/1.1.0/views_resources_200_percent.pak",
  "Program Files/TestApp/1.1.0/xinput1_3.dll",
  "Program Files/TestApp/1.1.0/locales/am.pak",
  "Program Files/TestApp/1.1.0/locales/ar.pak",
  "Program Files/TestApp/1.1.0/locales/bg.pak",
  "Program Files/TestApp/1.1.0/locales/bn.pak",
  "Program Files/TestApp/1.1.0/locales/ca.pak",
  "Program Files/TestApp/1.1.0/locales/cs.pak",
  "Program Files/TestApp/1.1.0/locales/da.pak",
  "Program Files/TestApp/1.1.0/locales/de.pak",
  "Program Files/TestApp/1.1.0/locales/el.pak",
  "Program Files/TestApp/1.1.0/locales/en-GB.pak",
  "Program Files/TestApp/1.1.0/locales/en-US.pak",
  "Program Files/TestApp/1.1.0/locales/es-419.pak",
  "Program Files/TestApp/1.1.0/locales/es.pak",
  "Program Files/TestApp/1.1.0/locales/et.pak",
  "Program Files/TestApp/1.1.0/locales/fa.pak",
  "Program Files/TestApp/1.1.0/locales/fake-bidi.pak",
  "Program Files/TestApp/1.1.0/locales/fi.pak",
  "Program Files/TestApp/1.1.0/locales/fil.pak",
  "Program Files/TestApp/1.1.0/locales/fr.pak",
  "Program Files/TestApp/1.1.0/locales/gu.pak",
  "Program Files/TestApp/1.1.0/locales/he.pak",
  "Program Files/TestApp/1.1.0/locales/hi.pak",
  "Program Files/TestApp/1.1.0/locales/hr.pak",
  "Program Files/TestApp/1.1.0/locales/hu.pak",
  "Program Files/TestApp/1.1.0/locales/id.pak",
  "Program Files/TestApp/1.1.0/locales/it.pak",
  "Program Files/TestApp/1.1.0/locales/ja.pak",
  "Program Files/TestApp/1.1.0/locales/kn.pak",
  "Program Files/TestApp/1.1.0/locales/ko.pak",
  "Program Files/TestApp/1.1.0/locales/lt.pak",
  "Program Files/TestApp/1.1.0/locales/lv.pak",
  "Program Files/TestApp/1.1.0/locales/ml.pak",
  "Program Files/TestApp/1.1.0/locales/mr.pak",
  "Program Files/TestApp/1.1.0/locales/ms.pak",
  "Program Files/TestApp/1.1.0/locales/nb.pak",
  "Program Files/TestApp/1.1.0/locales/nl.pak",
  "Program Files/TestApp/1.1.0/locales/pl.pak",
  "Program Files/TestApp/1.1.0/locales/pt-BR.pak",
  "Program Files/TestApp/1.1.0/locales/pt-PT.pak",
  "Program Files/TestApp/1.1.0/locales/ro.pak",
  "Program Files/TestApp/1.1.0/locales/ru.pak",
  "Program Files/TestApp/1.1.0/locales/sk.pak",
  "Program Files/TestApp/1.1.0/locales/sl.pak",
  "Program Files/TestApp/1.1.0/locales/sr.pak",
  "Program Files/TestApp/1.1.0/locales/sv.pak",
  "Program Files/TestApp/1.1.0/locales/sw.pak",
  "Program Files/TestApp/1.1.0/locales/ta.pak",
  "Program Files/TestApp/1.1.0/locales/te.pak",
  "Program Files/TestApp/1.1.0/locales/th.pak",
  "Program Files/TestApp/1.1.0/locales/tr.pak",
  "Program Files/TestApp/1.1.0/locales/uk.pak",
  "Program Files/TestApp/1.1.0/locales/vi.pak",
  "Program Files/TestApp/1.1.0/locales/zh-CN.pak",
  "Program Files/TestApp/1.1.0/locales/zh-TW.pak",
  "Program Files/TestApp/1.1.0/resources/app.asar",
  "Program Files/TestApp/1.1.0/resources/electron.asar",
  "Program Files/TestApp/1.1.0/resources/foo.ico",
  "users/Public/Desktop/TestApp.lnk",
  "users/Public/Start Menu/Programs/TestApp.lnk"
])