//noinspection SpellCheckingInspection
export const expectedWinContents = [
  "lib/net45/blink_image_resources_200_percent.pak",
  "lib/net45/content_resources_200_percent.pak",
  "lib/net45/content_shell.pak",
  "lib/net45/d3dcompiler_47.dll",
  "lib/net45/ffmpeg.dll",
  "lib/net45/icudtl.dat",
  "lib/net45/libEGL.dll",
  "lib/net45/libGLESv2.dll",
  "lib/net45/LICENSE.electron.txt",
  "lib/net45/LICENSES.chromium.html",
  "lib/net45/natives_blob.bin",
  "lib/net45/node.dll",
  "lib/net45/snapshot_blob.bin",
  "lib/net45/TestApp.exe",
  "lib/net45/TestApp_ExecutionStub.exe",
  "lib/net45/ui_resources_200_percent.pak",
  "lib/net45/Update.exe",
  "lib/net45/views_resources_200_percent.pak",
  "lib/net45/xinput1_3.dll",
  "lib/net45/locales/en-US.pak",
  "lib/net45/resources/app.asar",
  "lib/net45/resources/electron.asar",
  "TestApp.nuspec",
  "[Content_Types].xml",
  "_rels/.rels"
]