import { exec, TmpDir } from "builder-util"
import { outputFile } from "fs-extra"
import { readFile } from "fs/promises"
import * as path from "path"

export interface SelfSignedIdentity {
  /** Full certificate common name, e.g. `Developer ID Application: EB Test (TEAMID1234)`. */
  commonName: string
  /** base64-encoded PKCS#12, suitable for `CSC_LINK` / `MAC_CSC_LINK` / `WIN_CSC_LINK`. */
  p12Base64: string
  /** Password protecting the PKCS#12 and its private key. */
  password: string
  /**
   * PEM-encoded X.509 certificate (public part only). Present only for identities generated by
   * {@link createSelfSignedCodeSigningIdentity}; absent for identities sourced from `CSC_LINK`/env.
   */
  certPem?: string
  /**
   * DER-encoded X.509 certificate, base64-encoded. Present only for generated identities (see {@link certPem}).
   * Required by {@link installAdminTrustForCertificate}.
   */
  certDerBase64?: string
  /**
   * Uppercase SHA-1 fingerprint of the DER certificate, no separators (e.g. `A1B2…`). Keys the macOS trust store.
   * Present only for generated identities (see {@link certPem}).
   */
  sha1Fingerprint?: string
}

/** A {@link SelfSignedIdentity} produced by {@link createSelfSignedCodeSigningIdentity} (cert fields are always populated). */
export type GeneratedSelfSignedIdentity = SelfSignedIdentity & Required<Pick<SelfSignedIdentity, "certPem" | "certDerBase64" | "sha1Fingerprint">>

const PASSWORD = "eb-self-signed"

/**
 * Hard timeout (ms) for the `security` trust calls. Belt-and-suspenders: the admin-domain + passwordless-sudo
 * approach below is non-interactive, but if a runner ever lacks passwordless sudo (or `security` blocks for any
 * other reason) we want the test to fail in ~60s instead of hanging for the full 900s vitest timeout. builder-util's
 * `exec` forwards its options object straight to Node's `execFile`, which honours `timeout` by killing the child and
 * rejecting once it elapses — a clean guard with no reliance on a `timeout`/`gtimeout` binary (absent on macOS).
 */
const SECURITY_EXEC_TIMEOUT_MS = 60_000

export interface SelfSignedIdentityOptions {
  /**
   * Force the legacy SHA1/3DES PKCS#12 scheme. Required ONLY for macOS `security import`, which cannot read
   * PKCS#12 files produced with OpenSSL 3.x's default (stronger) algorithms. Leave `false` for everything
   * else (Windows' own openssl can't even emit them with `-legacy`). Default: `false` (modern PBES2/AES).
   */
  legacy?: boolean
  /**
   * Password protecting the PKCS#12. Default `eb-self-signed`. Pass `""` for the Windows identity: osslsigncode
   * attempts an empty-password read of the p12 first and, when stdin is not a TTY (vitest/CI), falls back to a
   * blocking console prompt that fails (`open_console ttyget`) for a *non-empty* password. An empty password
   * sidesteps the prompt entirely — which is why the previously committed `WIN_CSC_LINK` blob used one too.
   */
  password?: string
}

/**
 * Generates an ephemeral, untrusted self-signed code-signing identity (no developer membership required) and
 * returns it as a base64 PKCS#12. Intended solely for electron-builder's own signing tests. The produced
 * artifacts are NOT trusted/notarizable.
 *
 * @param commonName the full certificate common name (CN), e.g. `Developer ID Application: EB Test (TEAMID1234)`.
 */
export async function createSelfSignedCodeSigningIdentity(commonName: string, tmpDir: TmpDir, options: SelfSignedIdentityOptions = {}): Promise<GeneratedSelfSignedIdentity> {
  const password = options.password ?? PASSWORD
  const dir = await tmpDir.getTempDir({ prefix: "self-signed-identity" })
  const keyPath = path.join(dir, "key.pem")
  const certPath = path.join(dir, "cert.pem")
  const p12Path = path.join(dir, "cert.p12")
  const configPath = path.join(dir, "openssl.cnf")

  await outputFile(
    configPath,
    `[req]
distinguished_name = dn
x509_extensions = v3
prompt = no
[dn]
CN = ${commonName}
[v3]
basicConstraints = critical,CA:false
keyUsage = critical,digitalSignature
extendedKeyUsage = critical,codeSigning
`
  )

  await exec("openssl", ["req", "-x509", "-newkey", "rsa:2048", "-keyout", keyPath, "-out", certPath, "-days", "3650", "-nodes", "-config", configPath])

  // Apple's `security import` cannot read PKCS#12 files produced with OpenSSL 3.x's default (stronger)
  // algorithms, so the macOS identity forces the legacy SHA1/3DES scheme. LibreSSL (the system `openssl`)
  // already produces a compatible file and does not understand `-legacy`, so only pass it for OpenSSL >= 3.
  const p12Args = ["pkcs12", "-export", "-inkey", keyPath, "-in", certPath, "-out", p12Path, "-passout", `pass:${password}`, "-name", commonName]
  if (options.legacy && (await isOpenSsl3OrNewer())) {
    p12Args.push("-legacy", "-certpbe", "PBE-SHA1-3DES", "-keypbe", "PBE-SHA1-3DES", "-macalg", "sha1")
  }
  await exec("openssl", p12Args)

  const p12Base64 = (await readFile(p12Path)).toString("base64")
  const certPem = (await readFile(certPath)).toString("utf8")

  // DER form + SHA-1 fingerprint, needed to key the macOS admin-domain trust setting (see installAdminTrustForCertificate).
  const derPath = path.join(dir, "cert.der")
  await exec("openssl", ["x509", "-inform", "PEM", "-in", certPath, "-outform", "DER", "-out", derPath])
  const certDerBase64 = (await readFile(derPath)).toString("base64")
  const sha1Fingerprint = await fingerprintOfDerCert(derPath)

  return { commonName, p12Base64, password, certPem, certDerBase64, sha1Fingerprint }
}

/** Uppercase, separator-free SHA-1 fingerprint of a DER-encoded certificate. */
async function fingerprintOfDerCert(derCertPath: string): Promise<string> {
  const out = await exec("openssl", ["x509", "-noout", "-fingerprint", "-sha1", "-inform", "der", "-in", derCertPath])
  return out
    .toString()
    .replace(/^SHA1 Fingerprint=/, "")
    .replace(/:/g, "")
    .trim()
    .toUpperCase()
}

/**
 * macOS-only. Installs an ADMIN-domain trust setting for the given self-signed certificate so that it validates
 * as an OS-trusted code-signing identity. The setting is keyed on the certificate's SHA-1 fingerprint and grants
 * a `CodeSigning` trust-policy result. Ported from electron/packager's test/ci/codesign/{gen-trust.js,trust.xml}.
 *
 * The import MUST run in the admin domain (`-d`) via passwordless `sudo`: modifying USER-domain trust pops a
 * SecurityAgent GUI auth prompt that can never be answered on a headless CI runner, so `security` blocks forever
 * (the orphaned-process / 900s-timeout hang this replaces). The admin-domain import via passwordless `sudo` —
 * which GitHub-hosted macOS runners provide — is fully non-interactive, exactly as electron/packager does it.
 *
 * Pair every call with {@link removeAdminTrustForCertificate} (typically in a `finally`) to leave the trust
 * store clean.
 *
 * @returns the SHA-1 fingerprint used as the trust-store key.
 */
export async function installAdminTrustForCertificate(identity: Required<Pick<SelfSignedIdentity, "sha1Fingerprint" | "certDerBase64">>, tmpDir: TmpDir): Promise<string> {
  const dir = await tmpDir.getTempDir({ prefix: "self-signed-trust" })
  const plistPath = path.join(dir, "trust.plist")

  const certDer = Buffer.from(identity.certDerBase64, "base64")
  await outputFile(plistPath, buildTrustPlist(identity.sha1Fingerprint, certDer))
  // admin domain (`-d`) via passwordless sudo: non-interactive, no SecurityAgent GUI prompt.
  await exec("sudo", ["security", "trust-settings-import", "-d", plistPath], { timeout: SECURITY_EXEC_TIMEOUT_MS })
  return identity.sha1Fingerprint
}

/**
 * macOS-only. Removes the ADMIN-domain trust setting previously installed for `identity`
 * (see {@link installAdminTrustForCertificate}). Safe to call even if no such setting exists.
 *
 * Undoes an admin-domain `trust-settings-import` with `sudo security remove-trusted-cert -d <certDerFile>`,
 * which deletes the cert's admin-domain trust entry. The cert DER is written to a temp file in `tmpDir`.
 */
export async function removeAdminTrustForCertificate(identity: Required<Pick<SelfSignedIdentity, "certDerBase64">>, tmpDir: TmpDir): Promise<void> {
  const dir = await tmpDir.getTempDir({ prefix: "self-signed-untrust" })
  const certDerPath = path.join(dir, "cert.der")
  await outputFile(certDerPath, Buffer.from(identity.certDerBase64, "base64"))
  // `remove-trusted-cert -d` exits non-zero if the cert has no admin trust setting; ignore that so teardown is idempotent.
  await exec("sudo", ["security", "remove-trusted-cert", "-d", certDerPath], { timeout: SECURITY_EXEC_TIMEOUT_MS }).catch(() => {
    /* nothing to remove */
  })
}

/**
 * Builds a macOS trust-settings plist keyed on `fingerprint`, granting trust across the standard policies (the
 * `CodeSigning` entry is the one that matters here). `kSecTrustSettingsResult` 1 = "trust root". Mirrors
 * electron/packager's trust.xml. Each per-fingerprint record carries the `issuerName`/`serialNumber` hints from
 * packager's template, derived from the certificate's DER: `security trust-settings-import` validates structural
 * completeness and rejects the record as corrupted when they are missing.
 */
function buildTrustPlist(fingerprint: string, certDer: Buffer): string {
  const { issuerNameDer, serialNumberDer } = parseIssuerAndSerial(certDer)
  const issuerName = issuerNameDer.toString("base64")
  const serialNumber = serialNumberDer.toString("base64")

  const policy = (allowedError: number, policyOid: string, policyName: string) =>
    `				<dict>
					<key>kSecTrustSettingsAllowedError</key>
					<integer>${allowedError}</integer>
					<key>kSecTrustSettingsPolicy</key>
					<data>
						${policyOid}
					</data>
					<key>kSecTrustSettingsPolicyName</key>
					<string>${policyName}</string>
					<key>kSecTrustSettingsResult</key>
					<integer>1</integer>
				</dict>`

  const trustSettings = [
    policy(-2147409654, "KoZIhvdjZAED", "sslServer"),
    policy(-2147408896, "KoZIhvdjZAED", "sslServer"),
    policy(-2147409654, "KoZIhvdjZAEI", "SMIME"),
    policy(-2147408872, "KoZIhvdjZAEI", "SMIME"),
    policy(-2147409654, "KoZIhvdjZAEJ", "eapServer"),
    policy(-2147409654, "KoZIhvdjZAEL", "ipsecServer"),
    policy(-2147409654, "KoZIhvdjZAEQ", "CodeSigning"),
    policy(-2147409654, "KoZIhvdjZAEU", "AppleTimeStamping"),
    policy(-2147409654, "KoZIhvdjZAEC", "basicX509"),
  ].join("\n")

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>trustList</key>
		<dict>
			<key>${fingerprint}</key>
			<dict>
				<key>issuerName</key>
				<data>
				${issuerName}
				</data>
				<key>modDate</key>
				<date>2019-01-01T00:00:00Z</date>
				<key>serialNumber</key>
				<data>
				${serialNumber}
				</data>
				<key>trustSettings</key>
				<array>
${trustSettings}
				</array>
			</dict>
		</dict>
		<key>trustVersion</key>
		<integer>1</integer>
	</dict>
</plist>
`
}

/**
 * Extracts the issuer `Name` (the full DER SEQUENCE TLV, tag+length included) and the `serialNumber` INTEGER's
 * content octets from a DER-encoded X.509 certificate, via a minimal DER TLV walk (no extra deps). Layout:
 * `Certificate ::= SEQ { tbsCertificate SEQ { [0] version OPTIONAL, serialNumber INTEGER, signature AlgId SEQ,
 * issuer Name SEQ, ... } }`.
 */
function parseIssuerAndSerial(certDer: Buffer): { issuerNameDer: Buffer; serialNumberDer: Buffer } {
  const readTlv = (offset: number) => {
    const tag = certDer[offset]
    const lenByte = certDer[offset + 1]
    let length: number
    let headerLen: number
    if (lenByte < 0x80) {
      length = lenByte
      headerLen = 2
    } else {
      const numLenBytes = lenByte & 0x7f
      length = 0
      for (let i = 0; i < numLenBytes; i++) {
        length = length * 256 + certDer[offset + 2 + i]
      }
      headerLen = 2 + numLenBytes
    }
    const contentStart = offset + headerLen
    const end = contentStart + length
    return { tag, contentStart, end }
  }

  const cert = readTlv(0) // Certificate SEQUENCE
  const tbs = readTlv(cert.contentStart) // tbsCertificate SEQUENCE
  let p = tbs.contentStart
  if (certDer[p] === 0xa0) {
    // optional [0] EXPLICIT version
    p = readTlv(p).end
  }
  const serial = readTlv(p) // serialNumber INTEGER
  const serialNumberDer = certDer.subarray(serial.contentStart, serial.end)
  const signature = readTlv(serial.end) // signature AlgorithmIdentifier SEQUENCE
  const issuer = readTlv(signature.end) // issuer Name SEQUENCE (whole TLV)
  const issuerNameDer = certDer.subarray(signature.end, issuer.end)
  return { issuerNameDer, serialNumberDer }
}

async function isOpenSsl3OrNewer(): Promise<boolean> {
  const version = await exec("openssl", ["version"])
  const match = /^OpenSSL (\d+)\./.exec(version.trim())
  return match != null && Number(match[1]) >= 3
}
