import { exec, TmpDir } from "builder-util"
import { outputFile } from "fs-extra"
import { readFile } from "fs/promises"
import * as path from "path"

export interface SelfSignedIdentity {
  /** Full certificate common name, e.g. `Developer ID Application: EB Test (TEAMID1234)`. */
  commonName: string
  /** base64-encoded PKCS#12, suitable for `CSC_LINK` / `MAC_CSC_LINK` / `WIN_CSC_LINK`. */
  p12Base64: string
  /** Password protecting the PKCS#12 and its private key. */
  password: string
  /**
   * PEM-encoded X.509 certificate (public part only). Present only for identities generated by
   * {@link createSelfSignedCodeSigningIdentity}; absent for identities sourced from `CSC_LINK`/env.
   */
  certPem?: string
  /**
   * DER-encoded X.509 certificate, base64-encoded. Present only for generated identities (see {@link certPem}).
   * Required by {@link installUserTrustForCertificate}.
   */
  certDerBase64?: string
  /**
   * Uppercase SHA-1 fingerprint of the DER certificate, no separators (e.g. `A1B2…`). Keys the macOS trust store.
   * Present only for generated identities (see {@link certPem}).
   */
  sha1Fingerprint?: string
}

/** A {@link SelfSignedIdentity} produced by {@link createSelfSignedCodeSigningIdentity} (cert fields are always populated). */
export type GeneratedSelfSignedIdentity = SelfSignedIdentity & Required<Pick<SelfSignedIdentity, "certPem" | "certDerBase64" | "sha1Fingerprint">>

const PASSWORD = "eb-self-signed"

export interface SelfSignedIdentityOptions {
  /**
   * Force the legacy SHA1/3DES PKCS#12 scheme. Required ONLY for macOS `security import`, which cannot read
   * PKCS#12 files produced with OpenSSL 3.x's default (stronger) algorithms. Leave `false` for everything
   * else (Windows' own openssl can't even emit them with `-legacy`). Default: `false` (modern PBES2/AES).
   */
  legacy?: boolean
  /**
   * Password protecting the PKCS#12. Default `eb-self-signed`. Pass `""` for the Windows identity: osslsigncode
   * attempts an empty-password read of the p12 first and, when stdin is not a TTY (vitest/CI), falls back to a
   * blocking console prompt that fails (`open_console ttyget`) for a *non-empty* password. An empty password
   * sidesteps the prompt entirely — which is why the previously committed `WIN_CSC_LINK` blob used one too.
   */
  password?: string
}

/**
 * Generates an ephemeral, untrusted self-signed code-signing identity (no developer membership required) and
 * returns it as a base64 PKCS#12. Intended solely for electron-builder's own signing tests. The produced
 * artifacts are NOT trusted/notarizable.
 *
 * @param commonName the full certificate common name (CN), e.g. `Developer ID Application: EB Test (TEAMID1234)`.
 */
export async function createSelfSignedCodeSigningIdentity(commonName: string, tmpDir: TmpDir, options: SelfSignedIdentityOptions = {}): Promise<GeneratedSelfSignedIdentity> {
  const password = options.password ?? PASSWORD
  const dir = await tmpDir.getTempDir({ prefix: "self-signed-identity" })
  const keyPath = path.join(dir, "key.pem")
  const certPath = path.join(dir, "cert.pem")
  const p12Path = path.join(dir, "cert.p12")
  const configPath = path.join(dir, "openssl.cnf")

  await outputFile(
    configPath,
    `[req]
distinguished_name = dn
x509_extensions = v3
prompt = no
[dn]
CN = ${commonName}
[v3]
basicConstraints = critical,CA:false
keyUsage = critical,digitalSignature
extendedKeyUsage = critical,codeSigning
`
  )

  await exec("openssl", ["req", "-x509", "-newkey", "rsa:2048", "-keyout", keyPath, "-out", certPath, "-days", "3650", "-nodes", "-config", configPath])

  // Apple's `security import` cannot read PKCS#12 files produced with OpenSSL 3.x's default (stronger)
  // algorithms, so the macOS identity forces the legacy SHA1/3DES scheme. LibreSSL (the system `openssl`)
  // already produces a compatible file and does not understand `-legacy`, so only pass it for OpenSSL >= 3.
  const p12Args = ["pkcs12", "-export", "-inkey", keyPath, "-in", certPath, "-out", p12Path, "-passout", `pass:${password}`, "-name", commonName]
  if (options.legacy && (await isOpenSsl3OrNewer())) {
    p12Args.push("-legacy", "-certpbe", "PBE-SHA1-3DES", "-keypbe", "PBE-SHA1-3DES", "-macalg", "sha1")
  }
  await exec("openssl", p12Args)

  const p12Base64 = (await readFile(p12Path)).toString("base64")
  const certPem = (await readFile(certPath)).toString("utf8")

  // DER form + SHA-1 fingerprint, needed to key the macOS user-domain trust setting (see installUserTrustForCertificate).
  const derPath = path.join(dir, "cert.der")
  await exec("openssl", ["x509", "-inform", "PEM", "-in", certPath, "-outform", "DER", "-out", derPath])
  const certDerBase64 = (await readFile(derPath)).toString("base64")
  const sha1Fingerprint = await fingerprintOfDerCert(derPath)

  return { commonName, p12Base64, password, certPem, certDerBase64, sha1Fingerprint }
}

/** Uppercase, separator-free SHA-1 fingerprint of a DER-encoded certificate. */
async function fingerprintOfDerCert(derCertPath: string): Promise<string> {
  const out = await exec("openssl", ["x509", "-noout", "-fingerprint", "-sha1", "-inform", "der", "-in", derCertPath])
  return out
    .toString()
    .replace(/^SHA1 Fingerprint=/, "")
    .replace(/:/g, "")
    .trim()
    .toUpperCase()
}

/**
 * macOS-only. Installs a USER-domain trust setting for the given self-signed certificate so that it validates
 * as an OS-trusted code-signing identity (no `-d`/admin domain, hence no sudo). The setting is keyed on the
 * certificate's SHA-1 fingerprint and grants a `CodeSigning` trust-policy result. Ported from electron/packager's
 * test/ci/codesign/{gen-trust.js,trust.xml}.
 *
 * Pair every call with {@link removeUserTrustForCertificate} (typically in a `finally`) to leave the user's
 * trust store clean.
 *
 * @returns the SHA-1 fingerprint used as the trust-store key (pass it to `removeUserTrustForCertificate`).
 */
export async function installUserTrustForCertificate(identity: Required<Pick<SelfSignedIdentity, "sha1Fingerprint">>, tmpDir: TmpDir): Promise<string> {
  const dir = await tmpDir.getTempDir({ prefix: "self-signed-trust" })
  const plistPath = path.join(dir, "trust.plist")

  await outputFile(plistPath, buildTrustPlist(identity.sha1Fingerprint))
  // user domain (no `-d`): no sudo, only affects the current user's trust store.
  await exec("/usr/bin/security", ["trust-settings-import", plistPath])
  return identity.sha1Fingerprint
}

/**
 * macOS-only. Removes the USER-domain trust setting previously installed for `fingerprint`
 * (see {@link installUserTrustForCertificate}). Safe to call even if no such setting exists.
 */
export async function removeUserTrustForCertificate(fingerprint: string): Promise<void> {
  // `trust-settings-remove` exits non-zero if the cert has no user trust setting; ignore that so teardown is idempotent.
  await exec("/usr/bin/security", ["trust-settings-remove", fingerprint]).catch(() => {
    /* nothing to remove */
  })
}

/**
 * Builds a macOS trust-settings plist keyed on `fingerprint`, granting trust across the standard policies (the
 * `CodeSigning` entry is the one that matters here). `kSecTrustSettingsResult` 1 = "trust root". Mirrors
 * electron/packager's trust.xml. The `issuerName`/`serialNumber` hints from packager's template are omitted:
 * macOS resolves the trust entry by the certificate's SHA-1 fingerprint (the dictionary key), and `security
 * trust-settings-import` fills the issuer/serial from the matching installed certificate, so they need not be
 * pre-computed here (avoiding a brittle DER-issuer re-encode).
 */
function buildTrustPlist(fingerprint: string): string {
  const policy = (allowedError: number, policyOid: string, policyName: string) =>
    `				<dict>
					<key>kSecTrustSettingsAllowedError</key>
					<integer>${allowedError}</integer>
					<key>kSecTrustSettingsPolicy</key>
					<data>
						${policyOid}
					</data>
					<key>kSecTrustSettingsPolicyName</key>
					<string>${policyName}</string>
					<key>kSecTrustSettingsResult</key>
					<integer>1</integer>
				</dict>`

  const trustSettings = [
    policy(-2147409654, "KoZIhvdjZAED", "sslServer"),
    policy(-2147408896, "KoZIhvdjZAED", "sslServer"),
    policy(-2147409654, "KoZIhvdjZAEI", "SMIME"),
    policy(-2147408872, "KoZIhvdjZAEI", "SMIME"),
    policy(-2147409654, "KoZIhvdjZAEJ", "eapServer"),
    policy(-2147409654, "KoZIhvdjZAEL", "ipsecServer"),
    policy(-2147409654, "KoZIhvdjZAEQ", "CodeSigning"),
    policy(-2147409654, "KoZIhvdjZAEU", "AppleTimeStamping"),
    policy(-2147409654, "KoZIhvdjZAEC", "basicX509"),
  ].join("\n")

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>trustList</key>
		<dict>
			<key>${fingerprint}</key>
			<dict>
				<key>modDate</key>
				<date>2019-01-01T00:00:00Z</date>
				<key>trustSettings</key>
				<array>
${trustSettings}
				</array>
			</dict>
		</dict>
		<key>trustVersion</key>
		<integer>1</integer>
	</dict>
</plist>
`
}

async function isOpenSsl3OrNewer(): Promise<boolean> {
  const version = await exec("openssl", ["version"])
  const match = /^OpenSSL (\d+)\./.exec(version.trim())
  return match != null && Number(match[1]) >= 3
}
