import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "introduction",
    "cli",
    "targets",
    "donate",

    {
      type: "category",
      label: "Programmatic API",
      items: [
        "programmatic-usage",
        {
          type: "category",
          label: "Main Modules",
          items: [{ type: "autogenerated", dirName: "api" }],
        },
      ],
    },

    {
      type: "category",
      label: "Configuration",
      items: [
        "configuration",
        "contents",
        "file-patterns",
        "architecture",
        {
          type: "category",
          label: "macOS",
          items: ["mac", "dmg", "mas", "pkg"],
        },
        {
          type: "category",
          label: "Windows",
          items: ["win", "nsis", "appx", "msi", "msi-wrapped", "squirrel-windows"],
        },
        {
          type: "category",
          label: "Linux",
          items: ["linux", "appimage", "flatpak", "snap"],
        },
        "publish",
      ],
    },

    {
      type: "category",
      label: "Guides",
      items: [
        "hooks",
        "icons",
        "auto-update",
        {
          type: "category",
          label: "Code Signing",
          items: ["code-signing", "code-signing-win", "code-signing-mac", "notarization"],
        },
        "multi-platform-build",
        "github-actions",
        "troubleshooting",
      ],
    },

    {
      type: "category",
      label: "Tutorials",
      items: [
        "tutorials/adding-electron-fuses",
        "tutorials/loading-app-dependencies-manually",
        "tutorials/two-package-structure",
        "tutorials/macos-kernel-extensions",
        "tutorials/code-signing-windows-apps-on-unix",
        "tutorials/release-using-channels",
        "tutorials/test-update-on-s3-locally",
      ],
    },

    {
      type: "category",
      label: "Reference",
      items: ["glossary"],
    },
  ],
}

export default sidebars
