import * as fs from "fs"
import * as path from "path"
import type { ToolsetConfig } from "app-builder-lib/src/configuration"
import type { TestOptions } from "vitest"

const WIN_CODE_SIGN_VERSIONS: ToolsetConfig["winCodeSign"][] = ["0.0.0", "1.0.0", "1.1.0"]
const NSIS_VERSIONS: ToolsetConfig["nsis"][] = ["0.0.0", "1.0.0", "1.1.0"]

const GENERATED_DIR = path.resolve(__dirname, "../src/windows/generated")

interface SuiteConfig {
  name: string
  registerFn: string
  importPath: string
  outerDescribe?: { name: string; options?: TestOptions }
  winCodeSignVersions?: ToolsetConfig["winCodeSign"][] // set custom am
}

const SUITES: SuiteConfig[] = [
  {
    name: "winPackager",
    registerFn: "registerWinPackagerTests",
    importPath: "../winPackagerTestSuite",
  },
  {
    name: "portable",
    registerFn: "registerPortableTests",
    importPath: "../portableTestSuite",
    outerDescribe: { name: "portable" },
  },
  {
    name: "assistedInstaller",
    registerFn: "registerAssistedInstallerTests",
    importPath: "../assistedInstallerTestSuite",
    outerDescribe: { name: "assisted" },
  },
  {
    name: "msi",
    registerFn: "registerMsiTests",
    importPath: "../msiTestSuite",
    outerDescribe: { name: "msi", options: { sequential: true } },
  },
  {
    name: "msiWrapped",
    registerFn: "registerMsiWrappedTests",
    importPath: "../msiWrappedTestSuite",
    outerDescribe: { name: "msiWrapped", options: { sequential: true } },
  },
  {
    name: "squirrelWindows",
    registerFn: "registerSquirrelWindowsTests",
    importPath: "../squirrelWindowsTestSuite",
    outerDescribe: { name: "squirrel-windows", options: { sequential: true } },
  },
  {
    name: "appx",
    registerFn: "registerAppxTests",
    importPath: "../appxTestSuite",
    outerDescribe: { name: "AppX" },
    winCodeSignVersions: ["1.0.0", "1.1.0"],
  },
]

function renderFile(suite: SuiteConfig, winCodeSign: ToolsetConfig["winCodeSign"], nsis: ToolsetConfig["nsis"]): string {
  const toolsetsArg = `{ winCodeSign: "${winCodeSign}", nsis: "${nsis}" }`
  const label = `winCodeSign: ${winCodeSign}, nsis: ${nsis}`

  let body: string
  if (suite.outerDescribe) {
    const optionsPart = suite.outerDescribe.options ? `, ${JSON.stringify(suite.outerDescribe.options)}` : ""
    body = `describe.ifWindows("${suite.outerDescribe.name}"${optionsPart}, () => {
  describe("${label}", () => {
    ${suite.registerFn}(${toolsetsArg})
  })
})`
  } else {
    body = `describe("${label}", () => {
  ${suite.registerFn}(${toolsetsArg})
})`
  }

  return `// @generated — do not edit. Regenerated by generate-toolset-tests.ts on each test run.
import { ${suite.registerFn} } from "${suite.importPath}"

${body}
`
}

export function generateWindowsToolsetTests(): void {
  if (fs.existsSync(GENERATED_DIR)) {
    for (const f of fs.readdirSync(GENERATED_DIR)) {
      fs.rmSync(path.join(GENERATED_DIR, f))
    }
  } else {
    fs.mkdirSync(GENERATED_DIR, { recursive: true })
  }

  for (const suite of SUITES) {
    const wcsVersions = suite.winCodeSignVersions ?? WIN_CODE_SIGN_VERSIONS
    for (const wcs of wcsVersions) {
      for (const nsis of NSIS_VERSIONS) {
        const filename = `${suite.name}__wcs-${wcs}__nsis-${nsis}__Test.ts`
        fs.writeFileSync(path.join(GENERATED_DIR, filename), renderFile(suite, wcs, nsis), "utf8")
      }
    }
  }
}
