import * as fs from "fs"
import * as path from "path"
import type { ToolsetConfig } from "app-builder-lib/src/configuration"
import type { TestOptions } from "vitest"

const APPIMAGE_VERSIONS: ToolsetConfig["appimage"][] = ["0.0.0", "1.0.2", "1.0.3"]

const LINUX_GENERATED_DIR = path.resolve(__dirname, "../src/linux/generated")
const UPDATER_GENERATED_DIR = path.resolve(__dirname, "../src/updater/generated")

interface LinuxSuiteConfig {
  name: string
  registerFn: string
  importPath: string
  generatedDir: string
  argFormat: "object" | "scalar"
  innerDescribePrefix?: string
  outerDescribe: {
    name: string
    qualifier: "ifLinux" | "ifNotWindows"
    modifiers?: "heavy"[]
    options?: TestOptions
  }
}

const SUITES: LinuxSuiteConfig[] = [
  {
    name: "linuxPackager",
    registerFn: "registerLinuxPackagerTests",
    importPath: "../linuxPackagerTestSuite",
    generatedDir: LINUX_GENERATED_DIR,
    argFormat: "object",
    innerDescribePrefix: "AppImage toolset",
    outerDescribe: { name: "LinuxPackager", qualifier: "ifNotWindows" },
  },
  {
    name: "blackboxLinux",
    registerFn: "registerBlackboxLinuxTests",
    importPath: "../blackboxUpdateLinuxSuite",
    generatedDir: UPDATER_GENERATED_DIR,
    argFormat: "scalar",
    outerDescribe: { name: "linux", qualifier: "ifLinux", modifiers: ["heavy"], options: { sequential: true, retry: 1 } },
  },
  {
    name: "differentialLinux",
    registerFn: "registerDifferentialLinuxTests",
    importPath: "../differentialUpdateLinuxSuite",
    generatedDir: UPDATER_GENERATED_DIR,
    argFormat: "scalar",
    outerDescribe: { name: "AppImage", qualifier: "ifLinux", options: { sequential: true } },
  },
]

function buildDescribeCall(od: LinuxSuiteConfig["outerDescribe"]): string {
  const chain = [...(od.modifiers ?? []), od.qualifier].join(".")
  return `describe.${chain}`
}

function renderFile(suite: LinuxSuiteConfig, version: ToolsetConfig["appimage"]): string {
  const arg = suite.argFormat === "object" ? `{ appimage: "${version}" }` : `"${version}"`
  const od = suite.outerDescribe
  const describeCall = buildDescribeCall(od)
  const optionsPart = od.options ? `, ${JSON.stringify(od.options)}` : ""

  let innerBody: string
  if (suite.innerDescribePrefix) {
    innerBody = `  describe("${suite.innerDescribePrefix} ${version}", () => {
    ${suite.registerFn}(${arg})
  })`
  } else {
    innerBody = `  ${suite.registerFn}(${arg})`
  }

  const body = `${describeCall}("${od.name}"${optionsPart}, () => {
${innerBody}
})`

  return `// @generated — do not edit. Regenerated by generate-toolset-tests-linux.ts on each test run.
import { ${suite.registerFn} } from "${suite.importPath}"

${body}
`
}

function cleanAndEnsureDir(dir: string): void {
  if (fs.existsSync(dir)) {
    for (const f of fs.readdirSync(dir)) {
      fs.rmSync(path.join(dir, f))
    }
  } else {
    fs.mkdirSync(dir, { recursive: true })
  }
}

export function generateLinuxToolsetTests(): void {
  cleanAndEnsureDir(LINUX_GENERATED_DIR)
  cleanAndEnsureDir(UPDATER_GENERATED_DIR)

  for (const suite of SUITES) {
    for (const version of APPIMAGE_VERSIONS) {
      const filename = `${suite.name}__appimage-${version}__Test.ts`
      fs.writeFileSync(path.join(suite.generatedDir, filename), renderFile(suite, version), "utf8")
    }
  }
}
