import * as fs from "fs"
import * as path from "path"
import type { ToolsetConfig } from "app-builder-lib/src/configuration"
import { buildDescribeCall, cleanAndEnsureDir, GENERATED_TESTS_DIR, namedFn, resolveImportPath, TEST_SRC_DIR } from "./generate-toolset-tests-shared"
import type { SuiteConfig } from "./generate-toolset-tests-shared"
import type * as _LinuxPackagerSuite from "../src/linux/linuxPackagerTestSuite"
import type * as _BlackboxLinuxSuite from "../src/updater/blackboxUpdateLinuxSuite"
import type * as _DifferentialLinuxSuite from "../src/updater/differentialUpdateLinuxSuite"

const APPIMAGE_VERSIONS: ToolsetConfig["appimage"][] = ["0.0.0", "1.0.2", "1.0.3"]

const SUITES: SuiteConfig[] = [
  {
    name: "linuxPackager",
    registerFn: namedFn("registerLinuxPackagerTests" satisfies keyof typeof _LinuxPackagerSuite),
    importPath: "linux/linuxPackagerTestSuite",
    describeConfig: { name: "LinuxPackager", chain: ["ifNotWindows"] },
  },
  {
    name: "blackboxLinux",
    registerFn: namedFn("registerBlackboxLinuxTests" satisfies keyof typeof _BlackboxLinuxSuite),
    importPath: "updater/blackboxUpdateLinuxSuite",
    describeConfig: { name: "linux", chain: ["heavy", "ifLinux"] },
    describeOptions: { sequential: true, retry: 1 },
  },
  {
    name: "differentialLinux",
    registerFn: namedFn("registerDifferentialLinuxTests" satisfies keyof typeof _DifferentialLinuxSuite),
    importPath: "updater/differentialUpdateLinuxSuite",
    describeConfig: { name: "AppImage", chain: ["ifLinux"] },
    describeOptions: { sequential: true },
  },
]

function renderFile(suite: SuiteConfig, version: ToolsetConfig["appimage"]): string {
  const fnName = suite.registerFn.name
  const toolsetsArg = JSON.stringify({ appimage: version })
  const describeCall = buildDescribeCall(suite.describeConfig.chain)
  const optionsPart = suite.describeOptions ? `, ${JSON.stringify(suite.describeOptions)}` : ""

  const body = `${describeCall}("${suite.describeConfig.name}"${optionsPart}, () => {
  ${fnName}(${toolsetsArg})
})`

  const generatedDir = path.resolve(GENERATED_TESTS_DIR, suite.name)
  const importPath = resolveImportPath(generatedDir, TEST_SRC_DIR, suite.importPath)
  return `// @generated — do not edit. Regenerated by generate-toolset-tests-linux.ts on each test run.
import { ${fnName} } from "${importPath}"

${body}
`
}

export function generateLinuxToolsetTests(): void {
  for (const suite of SUITES) {
    const generatedDir = path.resolve(GENERATED_TESTS_DIR, suite.name)
    cleanAndEnsureDir(generatedDir)
    for (const version of APPIMAGE_VERSIONS) {
      const filename = `${suite.name}__appimage-${version}__Test.ts`
      fs.writeFileSync(path.join(generatedDir, filename), renderFile(suite, version), "utf8")
    }
  }
}
