import * as fs from "fs"
import * as path from "path"
import type { ToolsetConfig } from "app-builder-lib/src/configuration"
import { buildDescribeCall, cleanAndEnsureDir, namedFn, resolveImportPath } from "./generate-toolset-tests-shared"
import type { SuiteConfig } from "./generate-toolset-tests-shared"
import type * as _WinPackagerSuite from "../src/windows/winPackagerTestSuite"
import type * as _PortableSuite from "../src/windows/portableTestSuite"
import type * as _AssistedInstallerSuite from "../src/windows/assistedInstallerTestSuite"
import type * as _MsiSuite from "../src/windows/msiTestSuite"
import type * as _MsiWrappedSuite from "../src/windows/msiWrappedTestSuite"
import type * as _SquirrelWindowsSuite from "../src/windows/squirrelWindowsTestSuite"
import type * as _AppxSuite from "../src/windows/appxTestSuite"
import type * as _DifferentialWinSuite from "../src/updater/differentialUpdateWinSuite"
import type * as _BlackboxWinSuite from "../src/updater/blackboxUpdateWinSuite"

const WIN_CODE_SIGN_VERSIONS: ToolsetConfig["winCodeSign"][] = ["0.0.0", "1.0.0", "1.1.0"]

const TEST_SRC_DIR = path.resolve(__dirname, "../src")

interface WindowsSuiteConfig extends SuiteConfig {
  readonly winCodeSignVersions?: ToolsetConfig["winCodeSign"][]
}

const SUITES: WindowsSuiteConfig[] = [
  {
    name: "winPackager",
    registerFn: namedFn("registerWinPackagerTests" satisfies keyof typeof _WinPackagerSuite),
    importPath: "windows/winPackagerTestSuite",
    describeConfig: { name: "winPackager" },
  },
  {
    name: "portable",
    registerFn: namedFn("registerPortableTests" satisfies keyof typeof _PortableSuite),
    importPath: "windows/portableTestSuite",
    describeConfig: { name: "portable", chain: ["ifWindows"] },
  },
  {
    name: "assistedInstaller",
    registerFn: namedFn("registerAssistedInstallerTests" satisfies keyof typeof _AssistedInstallerSuite),
    importPath: "windows/assistedInstallerTestSuite",
    describeConfig: { name: "assisted", chain: ["ifWindows"] },
  },
  {
    name: "msi",
    registerFn: namedFn("registerMsiTests" satisfies keyof typeof _MsiSuite),
    importPath: "windows/msiTestSuite",
    describeConfig: { name: "msi", chain: ["ifWindows"] },
    describeOptions: { sequential: true },
  },
  {
    name: "msiWrapped",
    registerFn: namedFn("registerMsiWrappedTests" satisfies keyof typeof _MsiWrappedSuite),
    importPath: "windows/msiWrappedTestSuite",
    describeConfig: { name: "msiWrapped", chain: ["ifWindows"] },
    describeOptions: { sequential: true },
  },
  {
    name: "squirrelWindows",
    registerFn: namedFn("registerSquirrelWindowsTests" satisfies keyof typeof _SquirrelWindowsSuite),
    importPath: "windows/squirrelWindowsTestSuite",
    describeConfig: { name: "squirrel-windows", chain: ["ifWindows"] },
    describeOptions: { sequential: true },
  },
  {
    name: "appx",
    registerFn: namedFn("registerAppxTests" satisfies keyof typeof _AppxSuite),
    importPath: "windows/appxTestSuite",
    describeConfig: { name: "AppX", chain: ["ifWindows"] },
    winCodeSignVersions: ["1.0.0", "1.1.0"],
  },
  {
    name: "differentialWin",
    registerFn: namedFn("registerDifferentialWinTests" satisfies keyof typeof _DifferentialWinSuite),
    importPath: "updater/differentialUpdateWinSuite",
    describeConfig: { name: "differential-win", chain: ["ifWindows"] },
    describeOptions: { sequential: true },
  },
  {
    name: "blackboxWin",
    registerFn: namedFn("registerBlackboxWinTests" satisfies keyof typeof _BlackboxWinSuite),
    importPath: "updater/blackboxUpdateWinSuite",
    describeConfig: { name: "blackboxWin" },
    describeOptions: { sequential: true, retry: 1 },
  },
]

function renderFile(suite: WindowsSuiteConfig, winCodeSign: ToolsetConfig["winCodeSign"]): string {
  const fnName = suite.registerFn.name
  const toolsetsArg = JSON.stringify({ winCodeSign })
  const describeCall = buildDescribeCall(suite.describeConfig.chain)
  const optionsPart = suite.describeOptions ? `, ${JSON.stringify(suite.describeOptions)}` : ""

  const body = `${describeCall}("${suite.describeConfig.name}"${optionsPart}, () => {
  ${fnName}(${toolsetsArg})
})`

  const generatedDir = path.resolve(TEST_SRC_DIR, "generated", suite.name)
  const importPath = resolveImportPath(generatedDir, TEST_SRC_DIR, suite.importPath)
  return `// @generated — do not edit. Regenerated by generate-toolset-tests-windows.ts on each test run.
import { ${fnName} } from "${importPath}"

${body}
`
}

export function generateWindowsToolsetTests(): void {
  for (const suite of SUITES) {
    const generatedDir = path.resolve(TEST_SRC_DIR, "generated", suite.name)
    cleanAndEnsureDir(generatedDir)
    const wcsVersions = suite.winCodeSignVersions ?? WIN_CODE_SIGN_VERSIONS
    for (const wcs of wcsVersions) {
      const filename = `${suite.name}__wcs-${wcs}__Test.ts`
      fs.writeFileSync(path.join(generatedDir, filename), renderFile(suite, wcs), "utf8")
    }
  }
}
