name: Publish Any Commit
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Install node, pnpm and other dependencies
        uses: ./.github/actions/pnpm

      - name: Build
        run: pnpm compile

      - run: pnpm dlx pkg-pr-new publish --pnpm ./packages/*
